In [51]:
import numpy as np
import math

def gramschmidtQRdecomposeUsingGaussian(A):
    ncols = A.shape[1]
    AT = np.transpose(A)
    R = np.matmul(AT, A)
    R_augmented = np.hstack((R,AT))
    pivot_row = 0
    nrowsAugmented = R_augmented.shape[0]
    ncolsAugmented = R_augmented.shape[1]
    for col in range(ncolsAugmented):
        if (pivot_row >= nrowsAugmented):
            break
        normalizeFactor = R_augmented[pivot_row, col]
        for row in range(pivot_row + 1, nrowsAugmented):
            if (R_augmented[row][col] != 0):
                factor = R_augmented[row, col]
                R_augmented[row] -= (factor/normalizeFactor) * R_augmented[pivot_row]
        pivot_row += 1
    return (R_augmented[:,AT.shape[1]-1:],R_augmented[:,:ncols])

def norm(V):
    sum = 0
    for i in range(V.shape[0]):
        sum += V[i] * V[i]
    return math.sqrt(sum)

A = np.array([[0,-2,1], [1,3,1], [0,0,1],[1,1,5]], dtype=np.float64)
np.set_printoptions(suppress = True)
print(A)
Q,R = gramschmidtQRdecomposeUsingGaussian(A)

Q = np.transpose(Q)

print ("Q not normalized")
print(Q)

print("R not normalized")
print(R)

for i in range(R.shape[0]): 
    for j in range(R.shape[1]): 
        if (i == j):
            R[i,j] = math.sqrt(R[i,j])
        if (i < j):
            R[i][j] /= norm(Q[:,i])

print("Normalized R")
print(R)

for j in range(Q.shape[1]): 
    Q[:,j] /= norm(Q[:,j])

print("Normalized Q")
print(Q)

print(np.matmul(Q,R))



[[ 0. -2.  1.]
 [ 1.  3.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  5.]]
Q not normalized
[[ 0. -2. -1.]
 [ 1.  1. -1.]
 [ 0.  0.  1.]
 [ 1. -1.  1.]]
R not normalized
[[ 2.  4.  6.]
 [ 0.  6. -6.]
 [ 0.  0.  4.]]
Normalized R
[[ 1.41421356  2.82842712  4.24264069]
 [ 0.          2.44948974 -2.44948974]
 [ 0.          0.          2.        ]]
Normalized Q
[[ 0.         -0.81649658 -0.5       ]
 [ 0.70710678  0.40824829 -0.5       ]
 [ 0.          0.          0.5       ]
 [ 0.70710678 -0.40824829  0.5       ]]
[[ 0. -2.  1.]
 [ 1.  3.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  5.]]
