In [1]:
import numpy as np
def gramschmidtQRdecomposeUsingGaussian(A):
    nrows = A.shape[0]
    ncols = A.shape[1]
    AT = np.transpose(A)
    R = np.matmul(AT, A)
    R_augmented = np.hstack((R,AT))
    pivot_row = 0
    nrowsAugmented = R_augmented.shape[0]
    ncolsAugmented = R_augmented.shape[1]
    for col in range(ncolsAugmented):
        if (pivot_row >= nrowsAugmented):
            break
        normalizeFactor = R_augmented[pivot_row, col]
        for row in range(pivot_row + 1, nrowsAugmented):
            if (R_augmented[row][col] != 0):
                factor = R_augmented[row, col]
                R_augmented[row] -= (factor/normalizeFactor) * R_augmented[pivot_row]
        pivot_row += 1
    return (R_augmented[:,:ncols],R_augmented[:,AT.shape[1]-1:])

A = np.array([[0,-2,1], [1,3,1], [0,0,1],[1,1,5]], dtype=np.float64)
np.set_printoptions(suppress = True)
print(A)
Q,R = gramschmidtQRdecomposeUsingGaussian(A)

print(Q)
print(R)

[[ 0. -2.  1.]
 [ 1.  3.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  5.]]
[[ 2.  4.  6.]
 [ 0.  6. -6.]
 [ 0.  0.  4.]]
[[ 0.  1.  0.  1.]
 [-2.  1.  0. -1.]
 [-1. -1.  1.  1.]]
