In [1]:
import numpy as np

def Decompose_LU(A):

     # Check if A is square matrix
    if (A.shape[0] != A.shape[1]):
        print("Decompose_LU accepts only square matrix.")
        return
    
    nrows = ncols = A.shape[0]
    pivot_row = 0
    
    L = np.diag(np.full(nrows,1, dtype = np.float64))
    for col in range(ncols):
        normalizeFactor = A[pivot_row, col]
        for row in range(pivot_row + 1, nrows):
            if (A[row][col] != 0):
                factor = A[row, col]
                A[row] -= (factor/normalizeFactor) * A[pivot_row]
                L[row][col] = factor/normalizeFactor
        pivot_row += 1
    return (L,A)

A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]], dtype=np.float64)
#A = np.array([[3,2,4],[2,0,2],[4,2,3]], dtype=np.float64)
print(A)
L,U = Decompose_LU(A)

print(L)
print(U)

print(np.matmul(L,U))

[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]
[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]
[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]


In [2]:
import math

def Cholesky_Decomposition(A):

     # Check if A is square matrix
    if (A.shape[0] != A.shape[1]):
        print("Decompose_LU accepts only square matrix.")
        return
    
    nrows = ncols = A.shape[0]
    
    L = np.zeros((nrows,ncols), dtype = np.float64)
    for i in range(nrows):
        for j in range(i+1):
            sum = 0
            if(i == j):
                for k in range(j):
                    sum += pow(L[j][k], 2)
                L[i][j] = math.sqrt(A[i][j] - sum)
            else:  
                for k in range(j):
                    sum += (L[i][k] * L[j][k])
                if(L[j][j] > 0):
                    L[i][j] = (A[i][j] - sum) / L[j][j]
    return (L, np.transpose(L))
            
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]], dtype=np.float64)
#A = np.array([[3,2,4],[2,0,2],[4,2,3]], dtype=np.float64)
print(A)
L,LT = Cholesky_Decomposition(A)

print(L)
print(LT)

print(np.matmul(L,LT))

[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]
[[ 2.64575131  0.          0.          0.        ]
 [ 1.13389342  2.59119388  0.          0.        ]
 [-0.37796447  0.55131785  1.88499111  0.        ]
 [ 0.75592895 -1.87448068  0.16931058  1.37339999]]
[[ 2.64575131  1.13389342 -0.37796447  0.75592895]
 [ 0.          2.59119388  0.55131785 -1.87448068]
 [ 0.          0.          1.88499111  0.16931058]
 [ 0.          0.          0.          1.37339999]]
[[ 7.  3. -1.  2.]
 [ 3.  8.  1. -4.]
 [-1.  1.  4. -1.]
 [ 2. -4. -1.  6.]]


In [3]:
def gramschmidtQRdecompose(A):
    nrows = A.shape[0]
    ncols = A.shape[1]
    Q = np.zeros((nrows,ncols), dtype = np.float64)
    R = np.zeros((nrows,ncols), dtype = np.float64)
    R[0][0] = norm(A[:,0])
    Q[:,0] = A[:,0] / R[0][0]
    for i in range(1,ncols):
        Q[:,i] = A[:,i]
        for j in range(0,i):
            R[j][i] = np.matmul(np.matrix.transpose(Q[:,j]), Q[:,i]) 
            Q[:,i] = Q[:,i] - (R[j][i] * Q[:,j])
        R[i][i] = norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i][i]
    return Q,R

def norm(V):
    sum = 0
    for i in range(V.shape[0]):
        sum += V[i] * V[i]
    return math.sqrt(sum)

A = np.array([[12,-51,4], [6,167,-68], [-4,24,-42]], dtype=np.float64)
#A = np.array([[3,2,4],[2,0,2],[4,2,3]], dtype=np.float64)
print(A)
Q,R = gramschmidtQRdecompose(A)

print(Q)
print(R)

print(np.matmul(Q,R))

[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -42.]]
[[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
[[ 14.          21.         -13.71428571]
 [  0.         175.         -70.17142857]
 [  0.           0.          35.94285714]]
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -42.]]
