In [3]:
import numpy as np
from sympy import Matrix

#Using a random 4x3 matrix
C = np.array([[2,-11,3], [6,-2,3], [5,18,-4], [7,25,1]], dtype=np.float64)

CTC = C.T @ C

print(CTC)

eig_values, eig_vectors = np.linalg.eig(CTC)
M = Matrix(CTC)
print(M.charpoly())

print("The eigen values given by sympy package in python is: \n" + str(eig_values))
print("The eigen vector1 given by sympy package in python is: \n" + str(eig_vectors[:,0]) + "ᵀ")
print("The eigen vector2 given by sympy package in python is: \n" + str(eig_vectors[:,1]) + "ᵀ")
print("The eigen vector3 given by sympy package in python is: \n" + str(eig_vectors[:,2]) + "ᵀ")


[[ 114.  231.   11.]
 [ 231. 1074.  -86.]
 [  11.  -86.   35.]]
PurePoly(1.0*lambda**3 - 1223.0*lambda**2 + 103138.0*lambda - 1007475.0, lambda, domain='RR')
The eigen values given by sympy package in python is: 
[1132.73283645   79.01012846   11.25703509]
The eigen vector1 given by sympy package in python is: 
[-0.21977197 -0.97274019  0.07400541]ᵀ
The eigen vector2 given by sympy package in python is: 
[-0.84673264  0.15252645 -0.50968571]ᵀ
The eigen vector3 given by sympy package in python is: 
[-0.48450399  0.17467743  0.85717191]ᵀ


In [2]:
def calc_eigen_powermethod(A):
    # Choose the initial vector x 
    x = np.array([[1, 1, 1]]).T 

    # Define the tolerance 
    tol = 1e-6
  
    # Define the maximum number of iterations 
    max_iterations = 100
  
    previous_eigen_value = 0
  
    for i in range(max_iterations): 
        x = A @ x / np.linalg.norm(A @ x) 
        eig = (x.T @ A @ x) / (x.T @ x) 

        print("Eigen value after iteration " + str(i+1) + " is " + str(eig[0,0]))

        # Check if the eigen value is converged 
        if np.abs(eig - previous_eigen_value) < tol: 
            break
        
        previous_eigen_value = eig 
    
    return eig, x

A = CTC
print("Using Power Method")
eig1, x1 = calc_eigen_powermethod(A)
print("\nThe computed first eigen value is: " + str(eig1[0,0]))
print("The computed first eigen vector is: \n" + str(x1.T[0]) + "ᵀ" + "\n")

A = A - x1 @ x1.T @ A
eig2, x2 = calc_eigen_powermethod(A)
print("\nThe computed second eigen value is: " + str(eig2[0,0]))
print("The computed second eigen vector is: \n" + str(x2.T[0]) + "ᵀ" + "\n")

A = A - x1 @ x1.T @ A - x2 @ x2.T @ A
eig3, x3 = calc_eigen_powermethod(A)
print("\nThe computed third eigen value is: " + str(eig3[0,0]))
print("The computed third eigen vector is: \n" + str(x3.T[0]) + "ᵀ")

Using Power Method
Eigen value after iteration 1is 1126.8005986506819
Eigen value after iteration 2is 1132.7039381203708
Eigen value after iteration 3is 1132.7326958544818
Eigen value after iteration 4is 1132.7328357611377
Eigen value after iteration 5is 1132.732836441826

The computed first eigen value is: 1132.732836441826
The computed first eigen vector is: 
[ 0.21977348  0.97273992 -0.0740045 ]ᵀ

Eigen value after iteration 1is 78.7270143634
Eigen value after iteration 2is 79.00435780609935
Eigen value after iteration 3is 79.0100113166482
Eigen value after iteration 4is 79.01012608910729
Eigen value after iteration 5is 79.01012841891962
Eigen value after iteration 6is 79.01012846621335

The computed second eigen value is: 79.01012846621335
The computed second eigen vector is: 
[ 0.84673041 -0.15252751  0.5096891 ]ᵀ

Eigen value after iteration 1is 11.257035091960631
Eigen value after iteration 2is 11.257035091960633

The computed third eigen value is: 11.257035091960633
The compute