In [2]:
import numpy as np
from sympy import Matrix

#Using a random 4x3 matrix
C = np.array([[2,-11,3], [6,-2,3], [5,18,-4], [7,25,1]], dtype=np.float64)

C = np.array([
    [0, 0, 1, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 2, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 2, 1, 0, 1]
], dtype = np.float64)

CTC = C.T @ C

print(CTC)

eig_values, eig_vectors = np.linalg.eig(CTC)
M = Matrix(CTC)
print(M.charpoly())

print("The eigen values given by sympy package in python is: \n" + str(eig_values))
print("The eigen vector1 given by sympy package in python is: \n" + str(eig_vectors[:,0]) + "ᵀ")
print("The eigen vector2 given by sympy package in python is: \n" + str(eig_vectors[:,1]) + "ᵀ")
print("The eigen vector3 given by sympy package in python is: \n" + str(eig_vectors[:,2]) + "ᵀ")


[[1. 0. 1. 2. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [1. 1. 3. 2. 0. 0. 0.]
 [2. 0. 2. 9. 3. 0. 2.]
 [0. 0. 0. 3. 2. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 2. 1. 1. 3.]]
PurePoly(1.0*lambda**7 - 20.0*lambda**6 + 122.0*lambda**5 - 310.0*lambda**4 + 346.0*lambda**3 - 163.0*lambda**2 + 29.0*lambda - 1.0, lambda, domain='RR')
The eigen values given by sympy package in python is: 
[11.53955209  3.79217158  2.55619443  1.26011603  0.04468181  0.33922314
  0.46806092]
The eigen vector1 given by sympy package in python is: 
[-0.18744816 -0.02173007 -0.22902521 -0.87329723 -0.30004027 -0.02299511
 -0.24235812]ᵀ
The eigen vector2 given by sympy package in python is: 
[-0.25391302 -0.24047692 -0.67145282 -0.01875795  0.27882389  0.19911889
  0.55597409]ᵀ
The eigen vector3 given by sympy package in python is: 
[ 0.01605247 -0.30518578 -0.4749284   0.24995459  0.19619269 -0.41173678
 -0.64074248]ᵀ


In [3]:
def calc_eigen_powermethod(A):
    # Choose the initial vector x 
    x = np.array([[1, 1, 1, 1, 1, 1, 1]]).T 

    # Define the tolerance 
    tol = 1e-6
  
    # Define the maximum number of iterations 
    max_iterations = 100
  
    previous_eigen_value = 0
  
    for i in range(max_iterations): 
        x = A @ x / np.linalg.norm(A @ x) 
        eig = (x.T @ A @ x) / (x.T @ x) 

        print("Eigen value after iteration " + str(i+1) + " is " + str(eig[0,0]))

        # Check if the eigen value is converged 
        if np.abs(eig - previous_eigen_value) < tol: 
            break
        
        previous_eigen_value = eig 
    
    return eig, x

A = CTC
print("Using Power Method")
eig1, x1 = calc_eigen_powermethod(A)
print("\nThe computed first eigen value is: " + str(eig1[0,0]))
print("The computed first eigen vector is: \n" + str(x1.T[0]) + "ᵀ" + "\n")

A = A - x1 @ x1.T @ A
eig2, x2 = calc_eigen_powermethod(A)
print("\nThe computed second eigen value is: " + str(eig2[0,0]))
print("The computed second eigen vector is: \n" + str(x2.T[0]) + "ᵀ" + "\n")

A = A - x1 @ x1.T @ A - x2 @ x2.T @ A
eig3, x3 = calc_eigen_powermethod(A)
print("\nThe computed third eigen value is: " + str(eig3[0,0]))
print("The computed third eigen vector is: \n" + str(x3.T[0]) + "ᵀ")

Using Power Method
Eigen value after iteration 1 is 11.29875518672199
Eigen value after iteration 2 is 11.527402078337328
Eigen value after iteration 3 is 11.538922837382389
Eigen value after iteration 4 is 11.539517531544382
Eigen value after iteration 5 is 11.539549998893227
Eigen value after iteration 6 is 11.53955194879079
Eigen value after iteration 7 is 11.539552083021174

The computed first eigen value is: 11.539552083021174
The computed first eigen vector is: 
[0.18745627 0.02174391 0.2290566  0.87329307 0.30002728 0.02299635
 0.24235189]ᵀ

Eigen value after iteration 1 is 2.548245499842594
Eigen value after iteration 2 is 2.619046599890251
Eigen value after iteration 3 is 2.6958611036836246
Eigen value after iteration 4 is 2.8285634456202295
Eigen value after iteration 5 is 3.030510222959098
Eigen value after iteration 6 is 3.2708312187747914
Eigen value after iteration 7 is 3.4844793101513374
Eigen value after iteration 8 is 3.630390366269007
Eigen value after iteration 9 is 